name: asphanyx-dashboard

services:
  asphanyx-dashboard:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: ${APP_PORT}
    container_name: asphanyx-dashboard
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      API_BASE_URL: http://auth-saas-app:8081
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - default
      - auth_saas_backend

networks:
  auth_saas_backend:
    external: true
    name: auth-saas_backend
